import { WeaponConfig } from '../types/game';

export const WEAPON_DEFINITIONS: Record<string, WeaponConfig> = {
  M416: {
    id: 'M416',
    name: 'M416 Assault Rifle',
    category: 'AR',
    ammoType: '5.56mm',
    magazineSize: 30,
    damage: 41,
    fireRate: 11.5, // shots per sec
    recoil: 0.022,
    bulletSpeed: 880,
    zoomFov: 42, // 4x Scope zoom
    scopeName: '4x ACOG Scope',
    auto: true,
    color: '#38bdf8',
    description: 'Gold-standard 5.56mm tactical rifle. Exceptional stability and moddability across all combat ranges.',
  },
  AKM: {
    id: 'AKM',
    name: 'AKM Heavy Rifle',
    category: 'AR',
    ammoType: '7.62mm',
    magazineSize: 30,
    damage: 48,
    fireRate: 9.5,
    recoil: 0.038,
    bulletSpeed: 715,
    zoomFov: 50, // Red Dot zoom
    scopeName: 'Red Dot Sight',
    auto: true,
    color: '#f97316',
    description: 'Devastating 7.62mm stopping power. Demands strong recoil compensation in sustained spray.',
  },
  SCAR_L: {
    id: 'SCAR_L',
    name: 'SCAR-L',
    category: 'AR',
    ammoType: '5.56mm',
    magazineSize: 30,
    damage: 42,
    fireRate: 10.2,
    recoil: 0.019,
    bulletSpeed: 870,
    zoomFov: 46,
    scopeName: '2x Aimpoint Scope',
    auto: true,
    color: '#10b981',
    description: 'Extremely forgiving low horizontal recoil. Highly lethal in sustained burst engagements.',
  },
  BERYL_M762: {
    id: 'BERYL_M762',
    name: 'Beryl M762',
    category: 'AR',
    ammoType: '7.62mm',
    magazineSize: 30,
    damage: 46,
    fireRate: 12.0,
    recoil: 0.044,
    bulletSpeed: 740,
    zoomFov: 48,
    scopeName: 'Holographic Sight',
    auto: true,
    color: '#ef4444',
    description: 'Rapid-firing 7.62mm monster. Massive close-range DPS that rewards skilled drag-down control.',
  },
  AWM: {
    id: 'AWM',
    name: 'AWM Magnum Sniper',
    category: 'SNIPER',
    ammoType: '.300 Mag',
    magazineSize: 5,
    damage: 105,
    fireRate: 1.1, // Bolt action
    recoil: 0.08,
    bulletSpeed: 910,
    zoomFov: 18, // 8x High Magnification Scope
    scopeName: '8x CQB Scope',
    auto: false,
    color: '#eab308',
    description: 'Airdrop-exclusive king of marksman rifles. Can single-shot penetrate a Level 3 ballistic helmet.',
  },
  KAR98K: {
    id: 'KAR98K',
    name: 'Kar98k Marksman',
    category: 'SNIPER',
    ammoType: '7.62mm',
    magazineSize: 5,
    damage: 79,
    fireRate: 1.2,
    recoil: 0.065,
    bulletSpeed: 760,
    zoomFov: 24, // 6x Scope
    scopeName: '6x Tactical Scope',
    auto: false,
    color: '#d97706',
    description: 'Legendary bolt-action service rifle with crisp ballistic drop and lethal headshot multipliers.',
  },
  MINI14: {
    id: 'MINI14',
    name: 'Mini-14 DMR',
    category: 'DMR',
    ammoType: '5.56mm',
    magazineSize: 20,
    damage: 46,
    fireRate: 6.5,
    recoil: 0.024,
    bulletSpeed: 990,
    zoomFov: 32, // 4x Scope
    scopeName: '4x DMR Scope',
    auto: false,
    color: '#6366f1',
    description: 'High muzzle velocity DMR with almost instantaneous bullet travel. Unmatched for leading moving targets.',
  },
  UZI: {
    id: 'UZI',
    name: 'Micro UZI',
    category: 'SMG',
    ammoType: '9mm',
    magazineSize: 25,
    damage: 26,
    fireRate: 21.0, // 21 bullets/sec
    recoil: 0.016,
    bulletSpeed: 350,
    zoomFov: 58,
    scopeName: 'Iron Sights',
    auto: true,
    color: '#06b6d4',
    description: 'Unmatched rate of fire. Shreds enemies in close-quarters hipfire and indoor clearing.',
  },
  VECTOR: {
    id: 'VECTOR',
    name: 'Vector Tactical SMG',
    category: 'SMG',
    ammoType: '.45 ACP',
    magazineSize: 19,
    damage: 31,
    fireRate: 18.0,
    recoil: 0.018,
    bulletSpeed: 380,
    zoomFov: 52,
    scopeName: 'Red Dot Sight',
    auto: true,
    color: '#8b5cf6',
    description: 'Super-V recoil reduction system allows blistering fast .45 ACP bullet dumps with surgical precision.',
  },
  S12K: {
    id: 'S12K',
    name: 'S12K Combat Shotgun',
    category: 'SHOTGUN',
    ammoType: '12 Gauge',
    magazineSize: 5,
    damage: 96,
    fireRate: 4.0,
    recoil: 0.075,
    bulletSpeed: 350,
    zoomFov: 56,
    scopeName: 'Reflex Sight',
    auto: false,
    color: '#ec4899',
    description: 'Magazine-fed semi-automatic 12-gauge shotgun. Annihilates squads in stairwells and building breach.',
  },
  M249: {
    id: 'M249',
    name: 'M249 Squad Automatic Weapon',
    category: 'LMG',
    ammoType: '5.56mm',
    magazineSize: 100,
    damage: 45,
    fireRate: 13.0,
    recoil: 0.035,
    bulletSpeed: 915,
    zoomFov: 48,
    scopeName: '2x Reflex Sight',
    auto: true,
    color: '#f59e0b',
    description: '100-round belt-fed monster designed to shred enemy vehicles and pin down opposing squads.',
  },
  PANZERFAUST: {
    id: 'PANZERFAUST',
    name: 'Panzerfaust Rocket',
    category: 'SPECIAL',
    ammoType: 'Rocket',
    magazineSize: 1,
    damage: 220,
    fireRate: 0.6,
    recoil: 0.12,
    bulletSpeed: 250,
    zoomFov: 50,
    scopeName: 'Mechanical Range Finder',
    auto: false,
    color: '#ef4444',
    description: 'Single-shot disposable anti-armor launcher. Blasts enemy vehicles and compound rooms to smithereens.',
  },
};
